<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'title_en' => 'Laravel cơ bản',
                'title_bn' => null,
                'description_en' => 'Khóa học nhập môn Laravel cho người mới bắt đầu.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'free',
                'price' => 0.00,
                'old_price' => null,
                'subscription_price' => null,
                'start_from' => Carbon::now()->addDays(5),
                'duration' => 30,
                'lesson' => 12,
                'prerequisites_en' => 'Cần biết PHP cơ bản',
                'prerequisites_bn' => null,
                'difficulty' => 'beginner',
                'course_code' => 'LARV101',
                'image' => 'images/courses/laravel.png',
                'thumbnail_image' => 'images/courses/thumb/laravel.png',
                'thumbnail_video' => 'videos/courses/laravel_intro.mp4',
                'status' => 2,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'JavaScript nâng cao',
                'title_bn' => null,
                'description_en' => 'Nắm vững ES6+ và các framework JS hiện đại.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'paid',
                'price' => 990000,
                'old_price' => 1490000,
                'subscription_price' => 199000,
                'start_from' => Carbon::now()->addDays(10),
                'duration' => 45,
                'lesson' => 20,
                'prerequisites_en' => 'Yêu cầu có kiến thức JS trung cấp',
                'prerequisites_bn' => null,
                'difficulty' => 'advanced',
                'course_code' => 'JS302',
                'image' => 'images/courses/js.png',
                'thumbnail_image' => 'images/courses/thumb/js.png',
                'thumbnail_video' => 'videos/courses/js_intro.mp4',
                'status' => 2,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'Python cho Khoa học dữ liệu',
                'title_bn' => null,
                'description_en' => 'Phân tích và trực quan hóa dữ liệu với Python.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'subscription',
                'price' => 0.00,
                'old_price' => null,
                'subscription_price' => 299000,
                'start_from' => Carbon::now()->addDays(3),
                'duration' => 60,
                'lesson' => 25,
                'prerequisites_en' => 'Yêu cầu biết Python cơ bản',
                'prerequisites_bn' => null,
                'difficulty' => 'intermediate',
                'course_code' => 'PYDS201',
                'image' => 'images/courses/python.png',
                'thumbnail_image' => 'images/courses/thumb/python.png',
                'thumbnail_video' => 'videos/courses/python_intro.mp4',
                'status' => 2,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'ReactJS cơ bản',
                'title_bn' => null,
                'description_en' => 'Khóa học nhanh giúp bạn làm quen với ReactJS.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'free',
                'price' => 0.00,
                'old_price' => null,
                'subscription_price' => null,
                'start_from' => Carbon::now()->addDays(7),
                'duration' => 15,
                'lesson' => 8,
                'prerequisites_en' => 'Cần kiến thức JavaScript',
                'prerequisites_bn' => null,
                'difficulty' => 'beginner',
                'course_code' => 'REACT101',
                'image' => 'images/courses/react.png',
                'thumbnail_image' => 'images/courses/thumb/react.png',
                'thumbnail_video' => 'videos/courses/react_intro.mp4',
                'status' => 1,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'Django cho Web',
                'title_bn' => null,
                'description_en' => 'Xây dựng website mạnh mẽ với Django.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'paid',
                'price' => 799000,
                'old_price' => 999000,
                'subscription_price' => null,
                'start_from' => Carbon::now()->addDays(12),
                'duration' => 40,
                'lesson' => 18,
                'prerequisites_en' => 'Cần biết Python',
                'prerequisites_bn' => null,
                'difficulty' => 'intermediate',
                'course_code' => 'DJANGO202',
                'image' => 'images/courses/django.png',
                'thumbnail_image' => 'images/courses/thumb/django.png',
                'thumbnail_video' => 'videos/courses/django_intro.mp4',
                'status' => 2,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'Nhập môn Machine Learning',
                'title_bn' => null,
                'description_en' => 'Bắt đầu với các thuật toán và mô hình học máy.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'subscription',
                'price' => 0.00,
                'old_price' => null,
                'subscription_price' => 399000,
                'start_from' => Carbon::now()->addDays(20),
                'duration' => 50,
                'lesson' => 22,
                'prerequisites_en' => 'Cần kiến thức Python và thống kê',
                'prerequisites_bn' => null,
                'difficulty' => 'advanced',
                'course_code' => 'ML301',
                'image' => 'images/courses/ml.png',
                'thumbnail_image' => 'images/courses/thumb/ml.png',
                'thumbnail_video' => 'videos/courses/ml_intro.mp4',
                'status' => 0,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title_en' => 'HTML & CSS cơ bản',
                'title_bn' => null,
                'description_en' => 'Học thiết kế web với HTML và CSS từ đầu.',
                'description_bn' => null,
                'course_category_id' => null,
                'instructor_id' => null,
                'type' => 'free',
                'price' => 0.00,
                'old_price' => null,
                'subscription_price' => null,
                'start_from' => Carbon::now()->addDays(2),
                'duration' => 20,
                'lesson' => 10,
                'prerequisites_en' => 'Không yêu cầu kiến thức trước',
                'prerequisites_bn' => null,
                'difficulty' => 'beginner',
                'course_code' => 'HTML101',
                'image' => 'images/courses/html.png',
                'thumbnail_image' => 'images/courses/thumb/html.png',
                'thumbnail_video' => 'videos/courses/html_intro.mp4',
                'status' => 2,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
